export const jobIndustries = [
  "Accounting",
  "Advertising",
  "Affiliate marketing",
  "Aerospace engineering",
  "Animation",
  "Architecture",
  "Artificial intelligence",
  "Audio engineering",
  "Banking",
  "Biomedical engineering",
  "Chemical engineering",
  "Civil engineering",
  "Cloud computing",
  "Construction",
  "Content marketing",
  "Copywriting",
  "Customer service",
  "Cybersecurity",
  "Data science",
  "Database administration",
  "Dentistry",
  "DevOps",
  "Digital marketing",
  "Email marketing",
  "Electrical engineering",
  "Environmental engineering",
  "Film production",
  "Finance",
  "Graphic design",
  "Healthcare",
  "Human resources (HR)",
  "Insurance",
  "Legal",
  "Machine learning",
  "Marketing",
  "Mechanical engineering",
  "Medicine",
  "Mobile app development",
  "Music production",
  "Network engineering",
  "Nursing",
  "Pharmaceutical",
  "Product management",
  "Project management",
  "Property management",
  "Public relations (PR)",
  "Quality assurance (QA)",
  "Real estate",
  "Recruitment",
  "Sales",
  "Search engine optimization (SEO)",
  "Social media marketing",
  "Software development",
  "Talent acquisition",
  "Training and development",
  "User experience (UX) design",
  "User interface (UI) design",
  "Video game development",
  "Virtual reality (VR)",
  "Web development",
];

export const jobs = [
  {
    title: "Backend Developer",
    location: "Sydney",
    postedTime: "12 days ago",
    tags: ["Node.js", "Python", "Docker"],
    jobDetails:
      "mera lorem Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    title: "Frontend Developer",
    location: "Tokyo",
    postedTime: "25 days ago",
    tags: ["React", "JavaScript", "CSS"],
    jobDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    title: "Data Scientist",
    location: "Bangalore",
    postedTime: "3 days ago",
    tags: ["Python", "SQL", "Machine learning"],
    jobDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    title: "Network Engineer",
    location: "New York",
    postedTime: "8 days ago",
    tags: ["AWS", "Networking"],
    jobDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    title: "Full Stack Developer",
    location: "London",
    postedTime: "7 days ago",
    tags: ["Node.js", "React", "JavaScript", "SQL"],
    jobDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    title: "Software Engineer",
    location: "San Francisco",
    postedTime: "14 days ago",
    tags: ["Java", "Docker"],
    jobDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
];

export const cities = [
  // Indian cities
  "Ahmedabad",
  "Bangalore",
  "Chennai",
  "Delhi",
  "Hyderabad",
  "Kolkata",
  "Mumbai",
  "Pune",
  "Agra",
  "Ajmer",
  "Aligarh",
  "Allahabad",
  "Amritsar",
  "Aurangabad",
  "Bhopal",
  "Bhubaneswar",
  "Bikaner",
  "Chandigarh",
  "Coimbatore",
  "Dehradun",
  "Faridabad",
  "Ghaziabad",
  "Gurgaon",
  "Guwahati",
  "Gwalior",
  "Hubli-Dharwad",
  "Indore",
  "Jabalpur",
  "Jaipur",
  "Jalandhar",
  "Jamnagar",
  "Jamshedpur",
  "Jhansi",
  "Jodhpur",
  "Kanpur",
  "Kochi",
  "Kolhapur",
  "Kota",
  "Lucknow",
  "Ludhiana",
  "Madurai",
  "Mangalore",
  "Meerut",
  "Moradabad",
  "Mysore",
  "Nagpur",
  "Nashik",
  "Navi Mumbai",
  "Noida",
  "Patna",
  "Pondicherry",
  "Puducherry",
  "Patiala",
  "Patna",
  "Pimpri-Chinchwad",
  "Raipur",
  "Rajkot",
  "Ranchi",
  "Salem",
  "Sangli",
  "Siliguri",
  "Solapur",
  "Srinagar",
  "Surat",
  "Thane",
  "Thiruvananthapuram",
  "Tiruchirappalli",
  "Tirupur",
  "Udaipur",
  "Vadodara",
  "Varanasi",
  "Vasai-Virar",
  "Vijayawada",
  "Visakhapatnam",

  // Foreign cities
  "Abu Dhabi",
  "Amsterdam",
  "Athens",
  "Atlanta",
  "Auckland",
  "Bangkok",
  "Barcelona",
  "Beijing",
  "Berlin",
  "Boston",
  "Brisbane",
  "Brussels",
  "Budapest",
  "Buenos Aires",
  "Cairo",
  "Calgary",
  "Cape Town",
  "Chicago",
  "Copenhagen",
  "Dallas",
  "Denver",
  "Detroit",
  "Dubai",
  "Dublin",
  "Düsseldorf",
  "Edinburgh",
  "Frankfurt",
  "Geneva",
  "Hamburg",
  "Hanoi",
  "Helsinki",
  "Ho Chi Minh City",
  "Hong Kong",
  "Houston",
  "Istanbul",
  "Jakarta",
  "Johannesburg",
  "Kuala Lumpur",
  "Las Vegas",
  "Lisbon",
  "London",
  "Los Angeles",
  "Lyon",
  "Madrid",
  "Manila",
  "Melbourne",
  "Mexico City",
  "Miami",
  "Milan",
  "Minneapolis",
  "Montreal",
  "Moscow",
  "Munich",
  "Nairobi",
  "Nashville",
  "New York City",
  "Osaka",
  "Oslo",
  "Paris",
  "Perth",
  "Philadelphia",
  "Phoenix",
  "Prague",
  "Rio de Janeiro",
  "Riyadh",
  "Rome",
  "San Francisco",
  "Santiago",
  "São Paulo",
  "Seoul",
  "Shanghai",
  "Singapore",
  "Stockholm",
  "Sydney",
  "Taipei",
  "Tel Aviv",
  "Tokyo",
  "Toronto",
  "Vancouver",
  "Vienna",
  "Warsaw",
  "Washington, D.C.",
  "Zurich",
];

export const jobAPIs = [
  "200------https://rapidapi.com/letscrape-6bRBa3QguO5/api/jsearch/",
  {
    "500 per $5":
      "https://rapidapi.com/rockapis-rockapis-default/api/linkedin-api8/",
  },
  "https://rapidapi.com/mantiks-mantiks-default/api/indeed12/",
  "https://rapidapi.com/rockapis-rockapis-default/api/linkedin-api8/pricing",
];

export const googleJobSearchAPIkey = "AIzaSyCKof-MYdpY_gE1yo18Ngrj7aZY-VKLN7k";
